"""
Seeds the database with 100+ NGOs for realistic directory testing.

IMPORTANT - be upfront about what this actually contains:
  - 15 REAL, verifiable Pakistani NGOs (imported from seed_real_ngos.py),
    marked verified=True. These are genuine organizations.
  - ~90 SYNTHETIC sample entries, generated by combining real Pakistani
    cities with real cause categories (e.g. "Multan Water Trust"). These
    are NOT real organizations - they exist purely to give the directory
    enough volume to test search, filtering, and pagination realistically.
    They are marked verified=False so nothing implies they're legitimate,
    audited NGOs.

Run: python -m db.seed_100_ngos
"""

import random
from db.connection import get_connection
from db.seed_real_ngos import REAL_NGOS, PLACEHOLDER_NAMES

random.seed(42)  # reproducible output every run

CITIES = [
    ("Karachi", "Sindh"), ("Lahore", "Punjab"), ("Islamabad", "Islamabad Capital Territory"),
    ("Rawalpindi", "Punjab"), ("Faisalabad", "Punjab"), ("Multan", "Punjab"),
    ("Peshawar", "Khyber Pakhtunkhwa"), ("Quetta", "Balochistan"), ("Sialkot", "Punjab"),
    ("Gujranwala", "Punjab"), ("Hyderabad", "Sindh"), ("Bahawalpur", "Punjab"),
    ("Sargodha", "Punjab"), ("Sukkur", "Sindh"), ("Larkana", "Sindh"),
    ("Abbottabad", "Khyber Pakhtunkhwa"), ("Mardan", "Khyber Pakhtunkhwa"),
    ("Sahiwal", "Punjab"), ("Rahim Yar Khan", "Punjab"), ("Gujrat", "Punjab"),
    ("Sheikhupura", "Punjab"), ("Mingora", "Khyber Pakhtunkhwa"), ("Dera Ghazi Khan", "Punjab"),
    ("Nawabshah", "Sindh"), ("Mirpur", "Azad Kashmir"),
]

ORG_SUFFIXES = [
    "Foundation", "Welfare Trust", "Welfare Society", "Relief Organization",
    "Charitable Trust", "Development Foundation", "Community Trust", "Aid Society",
    "Welfare Association", "Support Network",
]

# category name -> (description template, mission template)
CAUSE_TEMPLATES = {
    "Education": ("Runs community schools and literacy programs for children in {city}.",
                  "Give every child in {city} access to a quality education."),
    "Healthcare": ("Operates a free medical clinic serving low-income families in {city}.",
                   "Make basic healthcare accessible to everyone in {city}."),
    "Flood Relief": ("Coordinates emergency shelter and supplies for flood-affected families near {city}.",
                     "Respond quickly and effectively when floods hit communities near {city}."),
    "Food": ("Distributes free meals and ration packs to families in need across {city}.",
             "No one in {city} should go hungry."),
    "Water": ("Installs clean water hand-pumps and filtration points in underserved parts of {city}.",
              "Bring safe drinking water to every household in {city}."),
    "Climate": ("Runs tree plantation and clean-energy awareness drives around {city}.",
               "Build climate resilience in and around {city}."),
    "Women": ("Offers vocational training and microloans to women entrepreneurs in {city}.",
             "Support women's economic independence in {city}."),
    "Children": ("Provides after-school care and nutrition support for children in {city}.",
                "Protect and nurture every child growing up in {city}."),
    "Orphans": ("Runs a residential care home for orphaned children in {city}.",
               "Give orphaned children in {city} a safe, loving home."),
    "Disability": ("Provides assistive devices and therapy support for people with disabilities in {city}.",
                  "Remove barriers facing people with disabilities in {city}."),
    "Animal Welfare": ("Runs a shelter and street-animal vaccination drive in {city}.",
                       "Protect and care for animals in {city}."),
    "Disaster Relief": ("Maintains a rapid-response relief team for emergencies in and around {city}.",
                        "Be first on the ground when disaster strikes near {city}."),
    "Blood Donation": ("Organizes regular blood donation drives and a donor registry in {city}.",
                       "Make sure {city}'s hospitals never run short of safe blood."),
    "Mental Health": ("Offers free counseling and mental health awareness sessions in {city}.",
                      "Make mental health support accessible and stigma-free in {city}."),
    "Legal Aid": ("Provides free legal consultation for low-income residents of {city}.",
                 "Ensure everyone in {city} can access justice regardless of income."),
    "Senior Citizens": ("Runs a day-care and home-visit program for elderly residents of {city}.",
                        "Make sure {city}'s elderly are never left without care."),
    "Ramadan": ("Organizes iftar distribution and Ramadan ration packs across {city}.",
               "Make sure every family in {city} can break their fast with dignity."),
}


def generate_synthetic_ngos(count):
    """Generates `count` unique synthetic NGOs from city x category x suffix combinations."""
    causes = list(CAUSE_TEMPLATES.keys())
    combos = []
    for city, province in CITIES:
        for cause in causes:
            for suffix in ORG_SUFFIXES:
                combos.append((city, province, cause, suffix))
    random.shuffle(combos)

    ngos = []
    seen_names = set()
    for city, province, cause, suffix in combos:
        name = f"{city} {cause} {suffix}"
        if name in seen_names:
            continue
        seen_names.add(name)

        desc_template, mission_template = CAUSE_TEMPLATES[cause]
        ngos.append({
            "name": name,
            "description": desc_template.format(city=city),
            "mission": mission_template.format(city=city),
            "city": city,
            "province": province,
            "website": "",
            "categories": [cause],
        })
        if len(ngos) >= count:
            break
    return ngos


def seed():
    conn = get_connection()
    cursor = conn.cursor(dictionary=True)

    try:
        for name in PLACEHOLDER_NAMES:
            cursor.execute("DELETE FROM ngos WHERE name = %s", (name,))
        conn.commit()

        cursor.execute("SELECT category_id, name FROM categories")
        cat_lookup = {row["name"]: row["category_id"] for row in cursor.fetchall()}

        def insert_ngo(ngo, verified):
            cursor.execute("SELECT ngo_id FROM ngos WHERE name = %s", (ngo["name"],))
            if cursor.fetchone():
                return False
            cursor.execute(
                """INSERT INTO ngos (name, description, mission, city, province, contact, website, verified)
                   VALUES (%s, %s, %s, %s, %s, %s, %s, %s)""",
                (ngo["name"], ngo["description"], ngo["mission"], ngo["city"], ngo["province"],
                 "See website for contact details", ngo.get("website", ""), verified)
            )
            ngo_id = cursor.lastrowid
            for cat_name in ngo["categories"]:
                cat_id = cat_lookup.get(cat_name)
                if cat_id:
                    cursor.execute(
                        "INSERT INTO ngo_categories (ngo_id, category_id) VALUES (%s, %s)",
                        (ngo_id, cat_id)
                    )
            return True

        real_count = 0
        for ngo in REAL_NGOS:
            if insert_ngo(ngo, verified=True):
                real_count += 1

        synthetic = generate_synthetic_ngos(count=95)
        synthetic_count = 0
        for ngo in synthetic:
            if insert_ngo(ngo, verified=False):
                synthetic_count += 1

        conn.commit()
        total = real_count + synthetic_count
        print(f"Inserted {real_count} real, verified NGOs.")
        print(f"Inserted {synthetic_count} synthetic sample NGOs (unverified, for demo volume).")
        print(f"Total NGOs in directory: {total}")

    except Exception:
        conn.rollback()
        raise
    finally:
        cursor.close()
        conn.close()


if __name__ == "__main__":
    seed()
